Добавляем графику в разметку
htmlacademy-htmlcss/2245591-sedona-36 pull request #2
Opened 2023-01-29 08:09 UTC by Schtock

2023-01-31 05:18 UTC, Dima-Dim requested changes
Убрать из разметки декоративные изображения.

2023-01-31 05:18 UTC, Dima-Dim commented on index.html
> +            <img class="advantages-image" src="images/advantages/advantages-photo-1.jpg" width="800" height="384" alt="Вывешенные флаги в городке">
https://up.htmlacademy.ru/htmlcss/36/module/2/item/19

2023-02-01 14:12 UTC, Dima-Dim requested changes

2023-02-01 14:12 UTC, Dima-Dim commented on catalog.html
> +<footer class="main-footer">
Что случилось с отступом?

2023-02-01 14:12 UTC, Dima-Dim commented on index.html
> +            <div class="accomodation-icon"></div>
https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06

2023-02-01 23:09 UTC, Schtock commented on index.html
> +            <div class="accomodation-icon"></div>
Дивы убрал, но не уверен насчет того, как правильно сделать.
Сейчас добавил заголовкам по второму классу, каждый из которых должен будет через CSS добавлять свою иконку.
Такой вариант подходит?

2023-02-03 03:47 UTC, Dima-Dim commented on index.html
> +            <div class="accomodation-icon"></div>
Не знаешь потому, что вы это ещё не проходили. Сейчас для этих изображений в коде ничего быть не должно. Вам расскажут о том, как правильно это сделать в разделе про декоративные элементы.

2023-02-03 03:53 UTC, merged