Проверяем макет по критериям
htmlacademy-htmlcss/2245591-sedona-36 pull request #9
Opened 2023-03-10 04:34 UTC by Schtock

2023-03-11 13:08 UTC, Dima-Dim requested changes
У тебя в блоке "НАСТОЯЩИЙ ГОРОДОК" над изображением есть синяя полоска, которой нет в макете.

2023-03-11 13:08 UTC, Dima-Dim commented on styles/styles.css
> +  font-family: "pt sans";
Почему PT Sans заменил на pt sans?

2023-03-11 13:08 UTC, Dima-Dim commented on styles/styles.css
> +.search-form > *:nth-child(1) {
А это всё для чего появилось?

2023-03-12 00:42 UTC, Schtock commented on styles/styles.css
> +  font-family: "pt sans";
Случайность. Менял написание цвета в hex-формате на прописные буквы через сочетание клавиш, которое работает во всем файле.
Исправлено.

2023-03-12 00:43 UTC, Schtock commented on styles/styles.css
> +.search-form > *:nth-child(1) {
Это добавил автопрефиксер.

2023-03-12 00:48 UTC, Schtock commented
> У тебя в блоке "НАСТОЯЩИЙ ГОРОДОК" над изображением есть синяя полоска, которой нет в макете.

Исправил, заменив object-fit на cover.

2023-03-13 10:29 UTC, merged